import type { BossConfig, ItemTemplate, RarityMeta, SlotKey, SlotMeta, StatKey } from "../simulation/types";

export const stageNames = [
  "实习摸鱼",
  "工位新手",
  "茶水间行者",
  "会议隐身者",
  "日报糊弄师",
  "带薪发呆者",
  "反卷斗士",
  "工位炼器师",
  "部门潜伏者",
  "无痕摸鱼宗师",
] as const;

export const stageExpNeeded = [60, 120, 220, 360, 560, 820, 1160, 1580, 2100, 2800];

export const slotMeta: Record<SlotKey, SlotMeta> = {
  computer: { key: "computer", label: "电脑", shortLabel: "脑", description: "主输出工位道具" },
  keyboard: { key: "keyboard", label: "键盘", shortLabel: "键", description: "连摸和反卷核心" },
  headset: { key: "headset", label: "耳机", shortLabel: "耳", description: "闪查与糊弄核心" },
  cup: { key: "cup", label: "水杯", shortLabel: "杯", description: "续杯和抗压核心" },
  chair: { key: "chair", label: "椅子", shortLabel: "椅", description: "装忙和防御核心" },
  badge: { key: "badge", label: "工牌", shortLabel: "牌", description: "身份与全能加成" },
  note: { key: "note", label: "便签", shortLabel: "签", description: "技巧和灵感核心" },
  snack: { key: "snack", label: "零食", shortLabel: "食", description: "收益和续航核心" },
};

export const rarityMeta: Record<string, RarityMeta> = {
  common: { key: "common", label: "普通", affixCount: 0, multiplier: 1, sellValue: 18, partValue: 3 },
  fine: { key: "fine", label: "精良", affixCount: 1, multiplier: 1.28, sellValue: 34, partValue: 6 },
  rare: { key: "rare", label: "稀有", affixCount: 2, multiplier: 1.65, sellValue: 58, partValue: 10 },
  epic: { key: "epic", label: "史诗", affixCount: 3, multiplier: 2.15, sellValue: 92, partValue: 16 },
  legendary: { key: "legendary", label: "传说", affixCount: 4, multiplier: 2.8, sellValue: 150, partValue: 25 },
  artifact: { key: "artifact", label: "摸鱼神器", affixCount: 4, multiplier: 3.5, sellValue: 240, partValue: 40 },
  legacy: { key: "legacy", label: "传世工位", affixCount: 5, multiplier: 4.4, sellValue: 420, partValue: 70 },
};

export const statLabels: Record<StatKey, string> = {
  efficiency: "摸鱼效率",
  hp: "抗压值",
  disguise: "伪装能力",
  speed: "摸鱼速度",
  inspiration: "灵感值",
  stability: "工位稳定",
  combo: "连摸",
  crit: "暴摸",
  evade: "闪查",
  counter: "反卷",
  busy: "装忙",
  heal: "续杯",
  bluff: "糊弄",
  burnout: "摆烂",
  deflect: "背锅转移",
  composure: "情绪稳定",
};

export const percentStats = new Set<StatKey>([
  "combo",
  "crit",
  "evade",
  "counter",
  "busy",
  "heal",
  "bluff",
  "burnout",
  "deflect",
  "composure",
]);

export const itemTemplates: ItemTemplate[] = [
  {
    id: "computer_dual_screen",
    name: "摸鱼双屏",
    slot: "computer",
    mainStats: ["efficiency", "crit"],
    affixBias: ["crit", "combo", "inspiration", "speed"],
    flavor: "左屏日报，右屏快乐。",
  },
  {
    id: "computer_old_laptop",
    name: "旧款笔记本",
    slot: "computer",
    mainStats: ["efficiency", "stability"],
    affixBias: ["busy", "disguise", "hp", "bluff"],
    flavor: "慢是慢了点，胜在没人怀疑。",
  },
  {
    id: "computer_stealth_window",
    name: "隐身窗口",
    slot: "computer",
    mainStats: ["efficiency", "bluff"],
    affixBias: ["evade", "bluff", "composure", "speed"],
    flavor: "看似表格，实则摸鱼。",
  },
  {
    id: "computer_workstation",
    name: "静音主机",
    slot: "computer",
    mainStats: ["efficiency", "inspiration"],
    affixBias: ["combo", "crit", "stability", "busy"],
    flavor: "风扇不响，心跳很响。",
  },
  {
    id: "keyboard_silent",
    name: "静音键盘",
    slot: "keyboard",
    mainStats: ["combo", "speed"],
    affixBias: ["combo", "counter", "crit", "efficiency"],
    flavor: "敲得很忙，产出随缘。",
  },
  {
    id: "keyboard_mechanical",
    name: "青轴伪装",
    slot: "keyboard",
    mainStats: ["efficiency", "counter"],
    affixBias: ["counter", "combo", "busy", "stability"],
    flavor: "声音很努力。",
  },
  {
    id: "keyboard_shortcut",
    name: "快捷键符箓",
    slot: "keyboard",
    mainStats: ["speed", "inspiration"],
    affixBias: ["evade", "combo", "inspiration", "bluff"],
    flavor: "一键切走所有心虚。",
  },
  {
    id: "keyboard_overtime",
    name: "加班残影",
    slot: "keyboard",
    mainStats: ["counter", "burnout"],
    affixBias: ["counter", "burnout", "hp", "crit"],
    flavor: "越累越不服。",
  },
  {
    id: "headset_noise",
    name: "降噪耳机",
    slot: "headset",
    mainStats: ["evade", "composure"],
    affixBias: ["evade", "bluff", "composure", "disguise"],
    flavor: "世界安静，老板也远。",
  },
  {
    id: "headset_meeting",
    name: "会议耳麦",
    slot: "headset",
    mainStats: ["bluff", "inspiration"],
    affixBias: ["bluff", "busy", "inspiration", "speed"],
    flavor: "嗯嗯好的，先对齐一下。",
  },
  {
    id: "headset_broken",
    name: "断线耳机",
    slot: "headset",
    mainStats: ["evade", "busy"],
    affixBias: ["evade", "busy", "deflect", "hp"],
    flavor: "听不清也是一种战术。",
  },
  {
    id: "headset_radio",
    name: "茶水间电台",
    slot: "headset",
    mainStats: ["speed", "bluff"],
    affixBias: ["evade", "speed", "combo", "composure"],
    flavor: "消息比老板先到。",
  },
  {
    id: "cup_thermos",
    name: "领导同款杯",
    slot: "cup",
    mainStats: ["hp", "heal"],
    affixBias: ["heal", "busy", "hp", "composure"],
    flavor: "端起来就像在思考战略。",
  },
  {
    id: "cup_coffee",
    name: "三倍咖啡",
    slot: "cup",
    mainStats: ["heal", "speed"],
    affixBias: ["heal", "speed", "crit", "inspiration"],
    flavor: "灵魂加速，手指发光。",
  },
  {
    id: "cup_water",
    name: "透明水杯",
    slot: "cup",
    mainStats: ["hp", "stability"],
    affixBias: ["hp", "disguise", "stability", "heal"],
    flavor: "无色无味，稳住工位。",
  },
  {
    id: "cup_bubble",
    name: "快乐奶茶",
    slot: "cup",
    mainStats: ["heal", "inspiration"],
    affixBias: ["heal", "combo", "inspiration", "burnout"],
    flavor: "续的是命，也是工资。",
  },
  {
    id: "chair_ergonomic",
    name: "人体工学椅",
    slot: "chair",
    mainStats: ["hp", "busy"],
    affixBias: ["busy", "hp", "stability", "disguise"],
    flavor: "坐姿认真，灵魂下班。",
  },
  {
    id: "chair_old",
    name: "吱呀老椅",
    slot: "chair",
    mainStats: ["counter", "hp"],
    affixBias: ["counter", "busy", "deflect", "hp"],
    flavor: "一响就是反击提示。",
  },
  {
    id: "chair_hidden",
    name: "半隐工位椅",
    slot: "chair",
    mainStats: ["disguise", "evade"],
    affixBias: ["evade", "disguise", "busy", "bluff"],
    flavor: "坐下以后存在感降低。",
  },
  {
    id: "chair_cushion",
    name: "午休坐垫",
    slot: "chair",
    mainStats: ["hp", "heal"],
    affixBias: ["heal", "hp", "composure", "burnout"],
    flavor: "看起来普通，躺赢关键。",
  },
  {
    id: "badge_newbie",
    name: "新人工牌",
    slot: "badge",
    mainStats: ["disguise", "stability"],
    affixBias: ["disguise", "composure", "hp", "busy"],
    flavor: "新人保护色，自带无辜。",
  },
  {
    id: "badge_veteran",
    name: "老员工工牌",
    slot: "badge",
    mainStats: ["stability", "deflect"],
    affixBias: ["deflect", "counter", "busy", "disguise"],
    flavor: "见过太多需求，已经不慌。",
  },
  {
    id: "badge_visitor",
    name: "访客吊牌",
    slot: "badge",
    mainStats: ["evade", "bluff"],
    affixBias: ["evade", "bluff", "speed", "deflect"],
    flavor: "没人知道你到底归谁管。",
  },
  {
    id: "badge_gold",
    name: "金边工牌",
    slot: "badge",
    mainStats: ["crit", "efficiency"],
    affixBias: ["crit", "efficiency", "combo", "inspiration"],
    flavor: "看着很像核心员工。",
  },
  {
    id: "note_todo",
    name: "待办便签",
    slot: "note",
    mainStats: ["inspiration", "bluff"],
    affixBias: ["inspiration", "bluff", "busy", "speed"],
    flavor: "写得越多，做得越少。",
  },
  {
    id: "note_report",
    name: "日报模板",
    slot: "note",
    mainStats: ["inspiration", "disguise"],
    affixBias: ["bluff", "disguise", "inspiration", "composure"],
    flavor: "持续推进，阶段闭环。",
  },
  {
    id: "note_excuse",
    name: "万能理由条",
    slot: "note",
    mainStats: ["bluff", "deflect"],
    affixBias: ["deflect", "bluff", "evade", "busy"],
    flavor: "先拉齐一下背景。",
  },
  {
    id: "note_focus",
    name: "专注贴纸",
    slot: "note",
    mainStats: ["efficiency", "stability"],
    affixBias: ["efficiency", "stability", "crit", "composure"],
    flavor: "贴在屏幕上，提醒自己先别笑。",
  },
  {
    id: "snack_cookie",
    name: "抽屉饼干",
    slot: "snack",
    mainStats: ["heal", "hp"],
    affixBias: ["heal", "hp", "inspiration", "busy"],
    flavor: "危急时刻补一口。",
  },
  {
    id: "snack_seed",
    name: "瓜子补给",
    slot: "snack",
    mainStats: ["combo", "speed"],
    affixBias: ["combo", "speed", "evade", "bluff"],
    flavor: "越嗑越有节奏。",
  },
  {
    id: "snack_energy",
    name: "能量棒",
    slot: "snack",
    mainStats: ["efficiency", "crit"],
    affixBias: ["crit", "efficiency", "burnout", "heal"],
    flavor: "短暂燃烧，长期摸鱼。",
  },
  {
    id: "snack_takeout",
    name: "外卖小票",
    slot: "snack",
    mainStats: ["inspiration", "deflect"],
    affixBias: ["deflect", "inspiration", "heal", "composure"],
    flavor: "凭此票据证明你很忙。",
  },
];

export const bosses: BossConfig[] = [
  {
    id: "boss_patrol",
    name: "老板巡查",
    title: "脚步声逼近",
    difficulty: 1,
    hp: 260,
    pressure: 34,
    disguise: 8,
    speed: 7,
    skillEvery: 3,
    skillName: "你现在忙吗",
    reward: { salary: 66, parts: 8, stageExp: 30 },
    notes: ["巡查型", "适合测试闪查和装忙"],
  },
  {
    id: "boss_meeting",
    name: "会议突袭",
    title: "临时拉会",
    difficulty: 2,
    hp: 420,
    pressure: 46,
    disguise: 14,
    speed: 8,
    skillEvery: 4,
    skillName: "大家同步一下",
    reward: { salary: 96, inspiration: 10, parts: 12, stageExp: 46 },
    notes: ["会议型", "糊弄和续杯更稳"],
  },
  {
    id: "boss_report",
    name: "日报审判",
    title: "请补充细节",
    difficulty: 3,
    hp: 620,
    pressure: 58,
    disguise: 20,
    speed: 9,
    skillEvery: 3,
    skillName: "这块再展开说说",
    reward: { salary: 136, inspiration: 16, performance: 3, parts: 18, stageExp: 66 },
    notes: ["复盘型", "考验抗压和反卷"],
  },
];
